import sqlite3

champions_data = [
    ('Garen', 'Top', "Soldato fiero e nobile, Garen combatte alla testa dell'Avanguardia Intrepida. È popolare tra i suoi compagni e rispettato anche dai nemici, soprattutto in quanto rampollo della prestigiosa famiglia della Guardia della Corona, a cui è affidata la difesa di Demacia e dei suoi ideali. Rivestito di un'armatura resistente alla magia e armato di una possente spada a due mani, Garen è pronto ad affrontare maghi e stregoni sul campo di battaglia, in un vero e proprio turbine di acciaio virtuoso.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg'),
    ('Darius', 'Top', "Non esiste simbolo più grande della potenza noxiana di Darius, il leader più temuto e temprato dalla battaglia della nazione. Partito da umili origini, è diventato la Mano di Noxus, falciando i nemici dell'impero, molti dei quali sono anch'essi noxiani. Sapendo che non dubita mai della giustezza della sua causa e non esita mai una volta sollevata la sua ascia, coloro che si oppongono al comandante della Legione Trifariana non possono aspettarsi alcuna pietà.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg'),
    ('Teemo', 'Top', "Teemo è l'impavido leader degli Esploratori Bandle, un gruppo di intrepidi yordle dediti all'esplorazione di Runeterra e alla scoperta del suo vasto mondo. Si avventura in lungo e in largo, affrontando sfide per guadagnarsi medaglie al merito, scrivendo nuove regole da aggiungere al sempre più ricco Manuale degli Esploratori Bandle e lasciando funghi esplosivi in ​​giro come regalo a sorpresa per i nuovi amici. In qualità di capo scout, con Teemo nei paraggi non succede mai niente di male!", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg'),
    ('Jax', 'Top', "Jax, il più grande maestro d'armi di Runeterra, è l'unico sopravvissuto dei Kohari, campioni votati alla difesa di Icathia. Ma quando il Vuoto si scatenò contro l'Orda Ascesa dell'impero Shuriman, Icathia fu distrutta, lasciando Jax senza casa né scopo. Raccolse l'ultima luce di Icathia, simbolo della sua speranza di sconfiggere un giorno il Vuoto, e ora viaggia per il mondo alla ricerca di guerrieri abbastanza forti da affrontare al suo fianco l'oscurità incombente.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_0.jpg'),
    ('Fiora', 'Top', "La duellante più temuta di tutta Valoran, Fiora è famosa tanto per i suoi modi bruschi e la sua astuzia politica quanto per la velocità del suo stocco. Nata nella nobile famiglia Laurent di Demacia, Fiora ha ereditato la casata dal padre in seguito a uno scandalo che li ha quasi distrutti; ora si dedica a restituire ai Laurent il posto che spetta loro di diritto tra i grandi e i potenti del regno.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_0.jpg'),
    ('Malphite', 'Top', "Malphite, una gigantesca creatura di pietra vivente, nacque dal cuore del grande costrutto Ixtali noto come il Monolito. Per secoli ha studiato l'equilibrio elementale di Runeterra, usando la sua immensa forza per mantenere l'ordine in un mondo spesso caotico e per annientare le tenebre che si annidano nelle sue profondità. Ora, risvegliato fin troppo spesso dai suoi sonni, Malphite sopporta i mutevoli temperamenti dei mortali, alla ricerca dell'unica causa degna dell'ultimo della sua specie.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg'),
    
    ('Lee Sin', 'Jungle', "Maestro delle antiche arti marziali di Ionia, Lee Sin è un combattente di principi che incanala l'essenza dello spirito del drago per affrontare qualsiasi sfida. Sebbene abbia perso la vista molti anni fa, il monaco guerriero ha dedicato la sua vita a proteggere la sua patria da chiunque osi turbarne il sacro equilibrio. I nemici che sottovalutano la sua indole meditativa dovranno fare i conti con i suoi leggendari pugni infuocati e i suoi calci rotanti infuocati.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_0.jpg'),
    ('Vi', 'Jungle', "Cresciuta nelle strade malfamate di Zaun, Vi è una donna irascibile, impulsiva e temibile, con scarso rispetto per l'autorità. È sempre stata un'abile sopravvissuta, grazie sia alle sue bravate giovanili in superficie, sia alla lunga e ingiustamente prolungata prigionia a Stillwater Hold. Ora, al servizio degli agenti di Piltover per mantenere la pace anziché infrangerla, brandisce dei potenti guanti esatecnologici in grado di trapassare muri e criminali con la stessa facilità.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg'),
    ('Master Yi', 'Jungle', "Il Maestro Yi ha temprato il suo corpo e affinato la sua mente, tanto che pensiero e azione sono diventati quasi un tutt'uno. Sebbene scelga di ricorrere alla violenza solo come ultima risorsa, la grazia e la velocità della sua spada assicurano sempre una rapida risoluzione. Essendo uno degli ultimi praticanti viventi dell'arte ionica del Wuju, Yi ha dedicato la sua vita a perpetuare l'eredità del suo popolo, scrutando i potenziali nuovi discepoli con le Sette Lenti dell'Intuizione per identificare i più meritevoli tra loro.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_0.jpg'),
    ('Warwick', 'Jungle', "Warwick è un mostro che si aggira per i grigi vicoli di Zaun. Trasformato da esperimenti atroci, il suo corpo è fuso con un intricato sistema di camere e pompe, macchinari che gli iniettano nelle vene una furia alchemica. Emerge dalle ombre per dare la caccia ai criminali che terrorizzano le profondità della città. Warwick è attratto dal sangue, impazzito dal suo odore... e nessuno che lo versi può sfuggirgli." , 'Facile',
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg'),
    ('Amumu', 'Jungle', "La leggenda narra che Amumu sia un'anima solitaria e malinconica proveniente dall'antica Shurima, che vaga per il mondo in cerca di un amico. Condannato da un'antica maledizione a rimanere solo per sempre, il suo tocco è morte, il suo affetto rovina. Coloro che affermano di averlo visto lo descrivono come un cadavere vivente, di piccola statura e avvolto in bende striscianti. Amumu ha ispirato miti, canti e leggende tramandate di generazione in generazione, tanto che è impossibile distinguere la verità dalla finzione.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg'),
    ('Shaco', 'Jungle', "Creato molto tempo fa come giocattolo per un principe solitario, il burattino incantato Shaco ora si diletta in omicidi e devastazioni. Corrotto dalla magia oscura e dalla perdita della persona amata, il burattino un tempo gentile trova piacere solo nella miseria delle povere anime che tormenta. Usa giocattoli e semplici trucchi con effetti letali, trovando esilaranti i risultati dei suoi sanguinosi giochi – e per coloro che odono una risata sinistra nel cuore della notte, il Giullare Demoniaco potrebbe averli designati come suoi prossimi giocattoli.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg'),
    
    ('Ahri', 'Mid', "Innatamente connessa alla magia del regno degli spiriti, Ahri è una vastaya simile a una volpe, capace di manipolare le emozioni delle sue prede e di assorbirne l'essenza, ricevendo frammenti di memoria e intuizioni da ogni anima che divora. Un tempo predatrice potente ma indomabile, Ahri ora viaggia per il mondo alla ricerca dei resti dei suoi antenati, cercando al contempo di sostituire i ricordi rubati con altri creati da lei stessa.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg'),
    ('Yasuo', 'Mid', "Yasuo, un ioniano dalla profonda determinazione, è un agile spadaccino che brandisce l'aria stessa contro i suoi nemici. Da giovane, orgoglioso, fu falsamente accusato dell'omicidio del suo maestro e, incapace di dimostrare la propria innocenza, fu costretto a uccidere il proprio fratello per legittima difesa. Col tempo, il vero assassino del suo maestro venne smascherato e suo fratello tornò misteriosamente dalla morte, eppure Yasuo non riuscì mai a perdonarsi per ciò che aveva fatto. Ora vaga per il mondo con solo il vento a guidare la sua spada.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg'),
    ('Zed', 'Mid', "Spietato e senza pietà, Zed è il leader dell'Ordine dell'Ombra, un'organizzazione da lui creata con l'intento di militarizzare le tradizioni magiche e marziali di Ionia per scacciare gli invasori noxiani. Durante la guerra, la disperazione lo spinse a sbloccare la forma segreta dell'ombra: una magia spirituale malevola tanto pericolosa e corruttrice quanto potente. Zed ha padroneggiato tutte queste tecniche proibite per distruggere qualsiasi cosa consideri una minaccia per la sua nazione o per il suo nuovo ordine.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg'),
    ('Lux', 'Mid', "Luxanna Crownguard proviene da Demacia, un regno isolato dove le abilità magiche sono viste con timore e sospetto. Capace di piegare la luce al suo volere, è cresciuta temendo di essere scoperta ed esiliata, ed è stata costretta a tenere segreto il suo potere per preservare il nobile status della sua famiglia. Ciononostante, l'ottimismo e la resilienza di Lux l'hanno portata ad abbracciare i suoi talenti unici, e ora cerca di portare maggiore tolleranza e comprensione nella sua terra natale.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg'),
    ('Katarina', 'Mid', "Determinata nel giudizio e letale in combattimento, Katarina è un'assassina noxiana di altissimo livello. Figlia maggiore del leggendario Generale Du Couteau, ha dimostrato il suo talento eliminando con rapidità nemici ignari. La sua ardente ambizione l'ha spinta a dare la caccia a obiettivi pesantemente sorvegliati, anche a rischio di mettere in pericolo i suoi alleati, ma qualunque sia la missione, Katarina non esiterà a compiere il suo dovere in un turbine di pugnali seghettati.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg'),
    ('Veigar', 'Mid', "Veigar, un entusiasta stregone yordle, ha abbracciato poteri che pochi altri osano anche solo avvicinare. Da abitante dallo spirito libero di Bandle City, un tempo desiderava ardentemente apprendere di più sulla magia celeste praticata dai mortali, ma la sua naturale curiosità fu distorta dalla prigionia nel Bastione Immortale. Ora, creatura ostinata con la furia oscura delle stelle al suo comando, Veigar è spesso sottovalutato dagli altri e, sebbene si creda veramente malvagio, c'è chi ancora si interroga sulle sue motivazioni più profonde...", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg'),
    
    ('Jinx', 'Bot', "Jinx, una criminale squilibrata e impulsiva proveniente dai bassifondi, è tormentata dalle conseguenze del suo passato, ma ciò non le impedisce di portare il suo personale e caotico pandemonio a Piltover e Zaun. Utilizza il suo arsenale di armi improvvisate con effetti devastanti, scatenando una raffica di esplosioni colorate e sparatorie, ispirando gli emarginati alla ribellione e alla resistenza con il caos che si lascia alle spalle.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg'),
    ('Ashe', 'Bot', "Nata nel Ghiaccio e appartenente alla tribù degli Avarosani, Ashe comanda l'orda più numerosa del nord. Stoica, intelligente e idealista, ma a disagio nel suo ruolo di leader, attinge alle magie ancestrali del suo lignaggio per brandire un arco di Ghiaccio Vero. Convinta che il suo popolo la consideri la reincarnazione dell'eroina mitologica Avarosa, Ashe spera di riunificare il Freljord riconquistando le antiche terre tribali.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg'),
    ('Caitlyn', 'Bot', "Rinomata come la migliore pacificatrice della città, Caitlyn Kiramman è anche la migliore risorsa di Piltover per liberare la città dai suoi sfuggenti elementi criminali. Spesso affianca Vi, fungendo da freddo contrappunto alla natura più impulsiva della sua compagna. Sebbene porti con sé un fucile hextech unico nel suo genere, l'arma più potente di Caitlyn è la sua intelligenza superiore, che le permette di tendere trappole elaborate a qualsiasi criminale abbastanza folle da operare nella Città del Progresso.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg'),
    ('Ezreal', 'Bot', "Un avventuriero audace, inconsapevolmente dotato di poteri magici, Ezreal esplora catacombe dimenticate, si scontra con antiche maledizioni e supera ostacoli apparentemente insormontabili con facilità. Il suo coraggio e la sua spavalderia non conoscono limiti, e preferisce improvvisare per uscire da ogni situazione, affidandosi in parte al suo ingegno, ma soprattutto al suo mistico guanto di Shuriman, che usa per scatenare devastanti esplosioni arcane. Una cosa è certa: quando Ezreal è nei paraggi, i guai non sono mai lontani. O forse lo sono ovunque.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg'),
    ('Vayne', 'Bot', "Shauna Vayne è una cacciatrice di mostri demaciana letale e inflessibile, che ha dedicato la sua vita a trovare e distruggere il demone che ha sterminato la sua famiglia. Armata di una balestra da polso e dardi d'argento, è determinata a eliminare i malfattori. Più astuta della sua preda, Vayne infligge una morte rapida e indolore: la sua personale forma di misericordia.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg'),
    ('Miss Fortune', 'Bot', "Sarah Fortune, capitana di Bilgewater famosa per la sua bellezza ma temuta per la sua spietatezza, si staglia come una figura austera tra i criminali incalliti della città portuale. Da bambina, fu testimone dell'omicidio della sua famiglia per mano del re dei predoni Gangplank, un atto che vendicò brutalmente anni dopo, facendo saltare in aria la sua nave ammiraglia mentre lui era ancora a bordo. Chi la sottovaluta si troverà di fronte a un'avversaria affascinante e imprevedibile... e, probabilmente, a un paio di proiettili nello stomaco.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg'),
    
    ('Thresh', 'Support', "Sadico e astuto, Thresh è uno spettro ambizioso e irrequieto delle Isole Ombra. Un tempo custode di innumerevoli segreti arcani, fu sconfitto da un potere superiore alla vita e alla morte, e ora si nutre tormentando e spezzando gli altri con una lenta e straziante inventiva. Le sue vittime soffrono ben oltre la loro breve esistenza terrena, mentre Thresh infligge agonia alle loro anime, imprigionandole nella sua lanterna sacrilega per torturarle per l'eternità.", 'Difficile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg'),
    ('Leona', 'Support', "Impregnata del fuoco del sole, Leona è una sacra guerriera dei Solari che difende il Monte Targon con la sua Lama Zenith e lo Scudo dell'Alba. La sua pelle risplende di fuoco stellare mentre i suoi occhi ardono del potere dell'Aspetto celeste che dimora in lei. Armata d'oro e gravata da un terribile fardello di antica conoscenza, Leona porta l'illuminazione ad alcuni, la morte ad altri.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_0.jpg'),
    ('Blitzcrank', 'Support', "Un colosso di metallo lucido, vapore e crepitio elettrico, Blitzcrank percorre le strade di Zaun instancabile impegno per migliorare la città sotterranea e portare aiuto a chi ne ha bisogno. Creato per scendere negli ambienti più corrosivi e pericolosi di Zaun per smaltire i rifiuti nocivi, si è evoluto oltre i limiti della sua programmazione originale, grazie al genio del suo inventore e al misterioso potere dell'hextech.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg'),
    ('Lulu', 'Support', "La maga yordle Lulu è nota per evocare illusioni oniriche e creature fantastiche mentre vaga per Runeterra con la sua fata compagna Pix. Lulu plasma la realtà a suo piacimento, deformando il tessuto del mondo e quelli che lei considera i limiti di questo regno fisico e mondano. Mentre altri potrebbero considerare la sua magia, nella migliore delle ipotesi, innaturale, e nella peggiore, pericolosa, lei crede che a tutti possa servire un tocco di incanto.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg'),
    ('Nami', 'Support', "Nami, una giovane e testarda vastaya del mare, fu la prima della tribù Marai ad abbandonare le onde e avventurarsi sulla terraferma, quando l'antico patto con i Targoniani venne infranto. Non avendo altra scelta, si assunse il compito di completare il sacro rituale che avrebbe garantito la sicurezza del suo popolo. Nel caos di questa nuova era, Nami affronta un futuro incerto con grinta e determinazione, usando il suo bastone evocatore di maree per invocare la forza degli oceani stessi.", 'Media', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_0.jpg'),
    ('Yuumi', 'Support', "Yuumi, una gatta magica proveniente da Bandle City, era un tempo la famiglio di Norra, un'incantatrice yordle. Quando la sua padrona scomparve misteriosamente, Yuumi divenne la Custode del Libro delle Soglie senziente di Norra, viaggiando attraverso i portali presenti nelle sue pagine per cercarla. Desiderosa di affetto, Yuumi cerca compagni amichevoli con cui collaborare nel suo viaggio, proteggendoli con scudi luminosi e una feroce determinazione. Mentre il Libro si sforza di mantenerla concentrata sul suo compito, Yuumi è spesso attratta dalle comodità terrene, come i sonnellini e il pesce. Alla fine, tuttavia, torna sempre alla sua missione per ritrovare la sua amica.", 'Facile', 
     'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg', 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg')
]

def initialize_sqlite():
    connection = sqlite3.connect('database.db')
    connection.execute('''
        CREATE TABLE IF NOT EXISTS champions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            role TEXT NOT NULL,
            lore TEXT NOT NULL,
            difficulty TEXT NOT NULL,
            image_vertical TEXT NOT NULL,
            image_horizontal TEXT NOT NULL,
            is_custom INTEGER DEFAULT 0
        )
    ''')
    connection.execute('DELETE FROM champions')
    cursor = connection.cursor()
    cursor.executemany(
        'INSERT INTO champions (name, role, lore, difficulty, image_vertical, image_horizontal) VALUES (?, ?, ?, ?, ?, ?)',
        champions_data
    )
    connection.commit()
    connection.close()
    print('Database inizializzato con successo!')


if __name__ == '__main__':
    initialize_sqlite()